Add qemu-system for {mips,mipsel}-unknown-linux-gnu

diff --git a/docker/linux-runner b/docker/linux-runner
--- a/docker/linux-runner
+++ b/docker/linux-runner
@@ -61,6 +61,15 @@ case "$arch" in
         driver9p="virtio-9p-pci"
         drivernet="virtio-net-pci"
         ;;
+    mips|mipsel)
+        # avoid kernel error
+        # https://blahcat.github.io/2017/07/14/building-a-debian-stretch-qemu-image-for-mipsel/
+        opt="-append nokaslr"
+        # fails if > 1
+        n=1
+        driver9p="virtio-9p-pci"
+        drivernet="virtio-net-pci"
+        ;;
 esac
 
 (
@@ -111,9 +120,22 @@ esac
 
 ) 200>$LOCK
 
-dbclient \
-    -t \
-    -p 10022 \
-    -y -y \
-    root@localhost \
-    "${@}"
+prog="$1"
+dir=$(dirname "$1")
+shift
+
+ssh="dbclient -t -p 10022 -y -y root@localhost"
+# In some system, programs in 9p file system fails to execute.
+# The workaround is to copy the file to the ramdisk fs and then execute it.
+# See https://github.com/chaos/diod/issues/35
+case "$arch" in
+    mips|mipsel)
+        $ssh mkdir -p "/tmp/$dir" ";" cp "$prog" "/tmp/$prog" ";" "/tmp/$prog" "${@}"
+        R=$!
+        $ssh rm -f "/tmp/$prog"
+        exit $R
+        ;;
+    *)
+        exec $ssh "$prog" "${@}"
+        ;;
+esac
